// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC_2015_Fancy;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Relay relaySubsystemSpike1;
    public static AnalogInput projectSubsystemAnalogInput0;
    public static Servo projectSubsystemServo0;
    public static SpeedController projectSubsystemSpeedController4;
    public static DigitalInput projectSubsystemDigitalInput0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        relaySubsystemSpike1 = new Relay(0);
        LiveWindow.addActuator("RelaySubsystem", "Spike 1", relaySubsystemSpike1);
        
        projectSubsystemAnalogInput0 = new AnalogInput(0);
        LiveWindow.addSensor("ProjectSubsystem", "Analog Input 0", projectSubsystemAnalogInput0);
        
        projectSubsystemServo0 = new Servo(9);
        LiveWindow.addActuator("ProjectSubsystem", "Servo 0", projectSubsystemServo0);
        
        projectSubsystemSpeedController4 = new Talon(4);
        LiveWindow.addActuator("ProjectSubsystem", "Speed Controller 4", (Talon) projectSubsystemSpeedController4);
        
        projectSubsystemDigitalInput0 = new DigitalInput(0);
        LiveWindow.addSensor("ProjectSubsystem", "Digital Input 0", projectSubsystemDigitalInput0);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
